### ISSUE TITLE
API Ruby per invio fatture allo SDI non funzionante

### ISSUE THREAD

**Issue by acarpe** [fattureincloud/fattureincloud-ruby-sdk#34]
da ieri continuiamo a ricevere il seguente errore quando proviamo ad inviare le fatture elettroniche allo SDI.
Lato nostro non abbiamo fatto rilasci ed accade per tutte le fatture.
Provando ad inviarle dall'interfaccia web le stesse fatture vengono inviate correttamente.

il codice utilizzato è il seguente:
```
@einvoice_api = FattureInCloud_Ruby_Sdk::IssuedEInvoicesApi.new
invoice = @issued_documents_api.get_issued_document(@company_id, invoice_id).data
    opts = {
      send_e_invoice_request: FattureInCloud_Ruby_Sdk::SendEInvoiceRequest.new
    }
@einvoice_api.send_e_invoice(@company_id, invoice_id, opts) unless ['accepted','not_delivered','sent','processing'].include?(invoice.ei_status)
```

ed il messaggio di errore ricevuto è il seguente (che non lascia molto spazio per capire cosa sta succedendo):
```
Error message: the server returns an error
HTTP status code: 422
Response headers: {"date"=>"Mon, 07 Nov 2022 10:28:00 GMT", "content-type"=>"application/json", "server"=>\"Microsoft-IIS/8.5", "strict-transport-security"=>"max-age=4838400; includeSubdomains;", "vary"=>"Authorization", "cache-control"=>"no-cache, private", "x-robots-tag"=>"noindex,nofollow,noarchive", "x-aspnet-version"=>"4.0.30319", "x-powered-by"=>"ASP.NET"}
Response body: {"error":{"message":"Invalid JSON data in request body.","validation_result":null}}
```

**Comment by emajo** [comment]
Ciao @acarpe, scusa per il ritardo nella risposta ma non controlliamo spesso le issues delle sdks, per questi problemi consiglio di scrivere sulla [nostra community](https://github.com/fattureincloud/api/discussions) che controlliamo giornalmente, questo problema era dovuto a un cambiamento nella validazione del json che non accettava più un body vuoto, il comportamento è stato riportato a come era in precedenza per cui chiudo questa issue.

Grazie,
Emanuele.
